README.md
Readme-first development begins with a good readme. This is an initial take at eyeglass' readme file. It attempts to capture what we are doing with eyeglass, example code, and the two primary use cases for eyeglass
1. Adding SASS files to a project
2. Adding custom functions using npm's dependency system
Some assumptions I have made with the readme
* convention wins over configuration and we want Sass files in `my_module/sass`
* we want to abstract the node-sass custom function registration so that we can offer enhanced functionality via eyeglass
=> Create the README.md

lib/module_importer.js, package.json
This change updates the module_importer to rely on the node.js native 'module' implementation for resolving module dependencies. In addition to removing a dependency, this also enables inclusion of globally installed node.js modules as well as modules installed using `npm link`.
Addresses some portion of the work from #2 by returning errors as if the item had been `require()`ed in node.js parlance.
=> Improves module resolution to rely on 'module' instead of node-resolve

lib/function_loader.js, lib/index.js, lib/module_importer.js, lib/util/discover.js, lib/util/resolve.js, package.json, test/fixtures/function_modules/node_modules/fn_module_a/eyeglass-exports.js, test/fixtures/function_modules/node_modules/fn_module_a/node_modules/transitive_fn/eyeglass-exports.js, test/fixtures/function_modules/node_modules/fn_module_a/node_modules/transitive_fn/package.json, test/fixtures/function_modules/node_modules/fn_module_a/package.json, test/fixtures/function_modules/package.json, test/test_function_loading.js, test/test_imports.js
This builds off of #4 and completes the WIP. The function loading works and passes all tests. Per the commit, I'd like to improve the error handling on this further. I've left the discovery util's `all()` method so that we can grab and report on conflicting versions of a module that have been loaded. I don't know the best place to surface this information however.
TODO
* change all case to weird_lower_case (btw, we should pull out rock-em-sock-em robots and settle our coding conventions here) [hint, hint](https://github.com/felixge/node-style-guide)
* improve error reporting (probably doesn't block the PR from landing)
=> Function discovery implemented

build/lint.js, build/test.js, gulpfile.js, lib/function_loader.js, lib/index.js, lib/module_importer.js, lib/util/capture.js, lib/util/discover.js, lib/util/files.js, lib/util/hash.js, lib/util/resolve.js, package.json, test/fixtures/basic_modules/node_modules/module_a/eyeglass-exports.js, test/fixtures/basic_modules/node_modules/module_a/node_modules/transitive_module/eyeglass-exports.js, test/fixtures/function_modules/node_modules/fn_module_a/eyeglass-exports.js, test/fixtures/function_modules/node_modules/fn_module_a/node_modules/transitive_fn/eyeglass-exports.js, test/test_function_loading.js, test/test_imports.js
This commit is uncomfortably large due to the amount of scrubbing that was done. That said, I'm really glad we're addressing this now.
* All files are now compatible with the ESLint file defined in [sass-eyeglass/eyeglass-dev-eslint](https://github.com/sass-eyeglass/eyeglass-dev-eslint).
* gulp was chosen as the build pipeline. It was easier than grunt to programatically invoke things for what we were doing
All tests are passing still, and now they all pass ESLint as well. This sets us up for CI integration.
=> Addition of coding conventions, gulp pipeline, and a code scrub

lib/function_loader.js, lib/module_importer.js, lib/util/discover.js, test/fixtures/basic_modules/node_modules/module_a/package.json, test/fixtures/basic_modules/package.json, test/fixtures/has_a_main_already/eyeglass-exports.js, test/fixtures/has_a_main_already/index.scss, test/fixtures/has_a_main_already/main.js, test/fixtures/has_a_main_already/package.json, test/fixtures/is_a_module/eyeglass-exports.js, test/fixtures/is_a_module/index.scss, test/fixtures/is_a_module/package.json, test/test_function_loading.js, test/test_imports.js
This lets code in tests written for an eyeglass module work exactly like it would if it were a consumer of the module using dependencies.
=> Correctly handle when an npm module is itself an eyeglass module.

README.md
This tripped me up. It's probably implicit, considering a user would be within the eyeglass repo when reading the other instructions. But Wondering if something more declarative like this would help?
=> declare need to clone eyeglass

lib/eyeglass-exports.js, lib/function_loader.js, lib/functions.js, lib/functions/asset_url.js, lib/functions/version.js, lib/index.js, lib/module_importer.js, lib/options_decorator.js, lib/util/discover.js, lib/util/sync_fn.js, lib/util/unquote.js, package.json, sass/assets.scss, test/fixtures/basic_modules/node_modules/module_a/package.json, test/test_assets.js, test/test_function_loading.js, test/test_imports.js, test/test_utils.js, test/test_version.js, test/testutils.js
This creates a single pattern (like importers) for custom functions. This code
can be removed when `node-sass` has similar support. For now, we have an
additional `.gyp` dependency when using this patch. The `deasync` library
allows us to create a blocking `while()` loop and drain the event queue. This
pattern is a bit better for our application than using a `node-fiber`, since
we want to not replumb the entire custom function flow.
Custom functions w/ this patch can either call `done()` (always the last
argument), or return a value synchronously.
Includes test.
=> Removes need to differentiate between sync/async custom functions

lib/module_importer.js, lib/util/files.js, test/fixtures/redundantly_named_modules/node_modules/module_a/eyeglass-exports.js, test/fixtures/redundantly_named_modules/node_modules/module_a/package.json, test/fixtures/redundantly_named_modules/node_modules/module_a/sass/_module_a.scss, test/fixtures/redundantly_named_modules/node_modules/module_a/sass/module_a/subdir/_module_a.scss, test/fixtures/redundantly_named_modules/node_modules/module_a/sass/module_a/subdir/module_a/_target.scss, test/fixtures/redundantly_named_modules/package.json, test/test_imports.js
The paths were being scanned incompletely. We were only checking for some of the possible include scenarios, and hadn't accounted for nested directories that shared names identical to the npm module name.
This fix rewrites the file util to be a bit smarter about path expansion and reduces the number of times we're writing forEach loops.
Adds tests to catch the nested-"susy" use case.
=> Path Fixes

lib/module_importer.js, lib/util/files.js
The original implementation of files.js that fixed #37 was not as maintainable.
This code change improves the readability of the files.js file by splitting
the namify calls out into their individual sections.
if-return checks were added to the individual namify lines to remove duplication
of file names to improve performance.
=> Cleans up files.js to reduce duplicates and improve readability

lib/function_loader.js, lib/util/discover.js, test/fixtures/function_modules/node_modules/fn_module_b/eyeglass-exports.js, test/fixtures/function_modules/node_modules/fn_module_b/package.json, test/fixtures/function_modules/package.json, test/test_function_loading.js
The function loader was not looking at devDependency items, which was causing
custom functions to not load for those following the readme. The custom
function search (done at `new Eyeglass()`) should be a deep search, and include
any devDependency items from a `package.json`.
Related to #40
=> Function Modules in devDependencies are loaded

lib/util/files.js, test/fixtures/app_assets/sass/advanced_includePaths.scss, test/fixtures/includable_scss/typography/_contrast.scss, test/test_imports.js
In particular when used in conjunction with includePaths.
Includes a test.
=> Make importer work with @import "foo/bar"

lib/util/files.js, package.json, test/fixtures/app_assets/sass/advanced_includePaths.scss, test/fixtures/app_assets/sass/dot_include.scss, test/fixtures/includable_scss/heavy.weights/_animal.noises.sass, test/fixtures/includable_scss/typography/_contrast.scss, test/test_imports.js
This change may yield some number of somewhat nonsensical searched filenames in some cases (like `.scss.scss`) but it also allows imports like `my.folder/my.styles` I believe it may also help with Asset Pipeline-influenced names like `.css.scss`.
=> Allow importing when there is a dot in a folder name

README.md
The previous example no longer works, since Eyeglass needs to be called with `new`, ie. `new Eyeglass({})`.
The new decorator syntax is a bit easier to read.
For this to work, #52 still needs to be fixed.
=> Use decorator syntax for Grunt example

lib/module_importer.js, test/fixtures/app_assets/sass/no_includePaths.scss, test/test_imports.js
Pull Request #51 to solve issue #47 is causing issues in Grunt for me. Specifically, if I include includePaths like this:
```
var eyeglass = new Eyeglass({
includePaths: [path.join(rootDir, 'node_modules','compass-mixins','lib')]
});
```
I get a `Fatal error: undefined is not a function`
If I exclude includePaths like this:
```
var eyeglass = new Eyeglass({});
```
I get a `Fatal error: Cannot read property 'forEach' of undefined`
This pull request maintains the logic in #51 when includePaths is a String (which is in the case in the tests), but also handles the previous logic of includePaths being an Array (which is the case when I run it with Grunt).
For reference, here are the versions I'm running:
eyeglass 0.6.1
grunt-sass 1.0.0
node-sass 3.3.2
libsass 3.2.5
@alanhogan @FransTwisk, if …
=> Handling the various different states of includePaths

lib/util/eyeglass_modules.js, package.json, test/fixtures/project_name_is_dep_name/node_modules/eyeglass-my-package/eyeglass-exports.js, test/fixtures/project_name_is_dep_name/node_modules/eyeglass-my-package/package.json, test/fixtures/project_name_is_dep_name/node_modules/eyeglass-my-package/sass/_index.scss, test/fixtures/project_name_is_dep_name/package.json, test/test_imports.js
This fixes a minor edge case where the project root's name matches the name of an eyeglass module, but they're not the same package.
e.g.
`package.json`
```json
{
"name": "foo",
"dependencies": {
"other-foo": "*"
}
}
```
`other-foo/package.json`
```json
{
"name": "other-foo",
"eyeglass": {
"name": "foo"
}
}
```
=> Fix edge case when project name matches eyeglass module name

lib/assets.js, package.json, test/test_assets.js
This allows `asset-url` uris to contain fragments (hash and query). These values get merged into the resulting url.
=> allow uri fragments within asset-url. fixes #75

lib/function_loader.js, lib/module_importer.js, lib/util/eyeglass_modules.js, site-src/docs/CHANGELOG.md, site-src/docs/eyeglass_modules/index.md, test/fixtures/is_a_module/package.json, test/fixtures/simple_module/package.json, test/fixtures/simple_module/sass/index.scss, test/test_imports.js
This PR makes simple eyeglass modules even simpler by not requiring an eyeglass exports file. For those modules that only provide sass files, they can just set a relative path in their package.json file. I suspect this will ease adoption because a small addition to package.json feels a simpler than adding a new javascript file especially to people who don't know js.
=> Optional eyeglass exports

sass/assets.scss, test/test_assets.js
`asset-uri` and `asset-url` currently both return `url(...)`
I'd expect `asset-uri` to return only the uri, not wrapped in `url(...)`
This also simplifies `asset-url` to leverage `asset-uri` to get the uri.
=> fix: asset-uri should return the uri not wrapped in url()

lib/options.js, lib/util/deprecator.js, test/test_assets.js, test/test_deprecate.js, test/test_function_loading.js, test/test_imports.js, test/test_options.js, test/test_semver.js, test/test_version.js, test/testutils.js
Per #94, this updates the test cases to use the new simplified API.
This also adds tests for deprecation warnings and tests for back-compat API support.
=> Clean up tests to use new API

site-src/docs/integrations/gulp.md
This PR will fix usage of deprecated API in the example code for gulp integration.
For eyeglass in #master.
=> Adjust example code to deprecations

lib/util/eyeglass_modules.js, test/fixtures/module_imports_eyeglass/node_modules/module_a/package.json, test/fixtures/module_imports_eyeglass/node_modules/module_a/sass/index.scss, test/fixtures/module_imports_eyeglass/package.json, test/test_imports.js
This issue was uncovered in https://github.com/sass-eyeglass/eyeglass-spriting/pull/19 where `eyeglass-spriting` tries to `@import "eyeglass/assets"` but doesn't declare `eyeglass` as a direct dependency.
=> allow eyeglass to be imported from anywhere

test/fixtures/sass_indented_import/sass/_part.sass, test/fixtures/sass_indented_import/sass/main.sass, test/fixtures/sass_indented_import/scss/_part.scss, test/fixtures/sass_indented_import/scss/main.scss, test/test_sass_indented.js
Here’s the issue [I mentioned](https://twitter.com/kennethormandy/status/684961843744387072) on Twitter. After testing it a bit more, it seems like Eyeglass is just interfering with or not processing with files with `.sass` indented syntax partials:
__Expected__
I can import a `.sass` and/or `.scss` partials, from `.sass` or `.scss` files, while using Eyeglass with Node-sass.
__Actual__
I can import `.scss` partials from `.sass` or `.scss` files, while using Eyeglass with Node-sass. If I import a `.sass` partial from either a `.sass` file or a `.scss` file, there is not CSS outputted from Node-sass.
This pull request adds one passing test for `.scss`, and one failing test for `.sass` demonstrating this. Hopefully it is just some oversight on my part regarding `.sass` syntax, but I can’t …
=> Adds failing test for importing a regular .sass partial

README.md
This was keeping me much to long from using eyeglass! After reading the README, I thought that eyeglass would automatically hook into node-sass. I thought that my modules where not discovered for some reason. It took me ages to understand that the issue was that node-sass is not "eyeglass-aware".
In short: I think this change makes it much easier for people to start using eyeglass. Kind of related: https://github.com/sass/node-sass/pull/1617
**Note**: The link only works on github. Should I change it to an absolute URL?
=> README clearification

docs/filesystem/index.md, lib/functions/fs.js, lib/functions/index.js, lib/importers/FSImporter.js, lib/index.js, lib/util/Options.js, sass/fs.scss, test/fixtures/filesystem/a.txt, test/fixtures/filesystem/subdir/imported.scss, test/test_fs.js
This module for eyeglass implements the basics of the filesystem API I'd like to add to eyeglass. This forms the foundation of what is needed for a eyeglass module to implement an assets override in pure sass (the assets code allows an eyeglass module to create an assets.scss file that overrides the default assets importer). When designing the assets module, we planned to make it easy for developers to use Sass to maintain their assets API and issue deprecation warnings, etc, all without dropping into javascript.
Beyond assets, there's obviously lots of things that I think people will use this for. Especially once we add more functionality to it (E.g. directory listings).
But I wanted to get initial feedback to make sure no one hates what I've made so far.
There's a bunch of docs in the …
=> Filesystem Module

lib/functions/fs.js, lib/importers/FSImporter.js, package.json, test/test_assets.js, test/test_fs.js
This cleans up a few lint warnings:
```
[15:45:12] Starting 'lint'...
test/test_fs.js
5:5  warning  "tmp" is defined but never used  no-unused-vars
9:5  warning  "fse" is defined but never used  no-unused-vars
✖ 2 problems (0 errors, 2 warnings)
lib/importers/FSImporter.js
3:5   warning  "fs" is defined but never used                   no-unused-vars
5:5   warning  "efs" is defined but never used                  no-unused-vars
17:11  warning  Identifier 'absolute_path' is not in camel case  camelcase
19:9   warning  Identifier 'absolute_path' is not in camel case  camelcase
21:9   warning  Identifier 'absolute_path' is not in camel case  camelcase
23:9   warning  Identifier 'absolute_path' is not in camel case  camelcase
25:11  warning  Identifier 'absolute_path' is not in camel case …
```
=> cleanup some lint warnings

build/coverage.js, gulpfile.js, lib/assets/AssetsSource.js, lib/functions/fs.js, lib/importers/FSImporter.js, lib/importers/ImportUtilities.js, lib/modules/EyeglassModules.js, lib/util/NameExpander.js, lib/util/package.js, test/test_fs.js, test/test_options.js, test/test_semver.js, test/test_utils.js
This includes:
- several more test cases
- several `istanbul ignore` statements for things like `fs` and `glob` error handling which probably isn't worth writing test coverage for right now
- `gulp test:all` task that will run lint and test coverage in one pass so I don't have to run both individually
- `TODO` comments where we still need a test case
Test coverage before:
```
----------------------|----------|----------|----------|----------|----------------|
File                  |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------------------|----------|----------|----------|----------|----------------|
lib/                 |      100 |      100 |      100 |      100 |                |
eyeglass-exports.js |      100 |      100 |      100 |      100 | …
```
=> increase test coverage and thresholds

package.json
Currently all files not excluded by `.gitignore` end up in the published npm artifact.
This explicitly whitelists the files to include in the published artifact.
Included files:
- `lib/*`
- `sass/*`
See for reference: https://docs.npmjs.com/files/package.json#files
Verified against a few different projects via `npm install ~/workspace/eyelgass`
```
$ npm install ~/workspace/eyeglass && tree -I "node_modules" node_modules/eyeglass
...
node_modules/eyeglass
├── LICENSE
├── README.md
├── lib
│   ├── assets
│   │   ├── Assets.js
│   │   ├── AssetsCollection.js
│   │   └── AssetsSource.js
│   ├── eyeglass-exports.js
│   ├── functions
│   │   ├── asset-uri.js
│   │   ├── fs.js
│   │   ├── index.js
│   │   ├── normalize-uri.js
│   │   └── version.js
│   ├── importers
│   │   ├── AssetImporter.js …
```
=> whitelist files to include in published npm artifact

lib/modules/EyeglassModule.js, test/fixtures/symlinked_modules/mymodule/node_modules/shared_dep/package.json, test/fixtures/symlinked_modules/mymodule/node_modules/shared_dep/sass/index.scss, test/fixtures/symlinked_modules/mymodule/package.json, test/fixtures/symlinked_modules/mymodule/sass/index.scss, test/fixtures/symlinked_modules/project/node_modules/shared_dep/package.json, test/fixtures/symlinked_modules/project/node_modules/shared_dep/sass/index.scss, test/fixtures/symlinked_modules/project/package.json, test/test_modules.js
When an eyeglass module was being developed on and being used in another project via `npm link`, the linked module would not find its import dependencies because the symlink dir was being compared to the realpath in some cases. We now always use the real path of an eyeglass module for that modules root `path`.
=> Handle eyeglass module dependencies of symlinked node modules

lib/functions/normalize-uri.js, sass/assets.scss, test/test_assets.js
The main change here is to not `quote()` the output directly in `eyeglass-normalize-uri`. This caused issues when the resulting value was set as a key on `$eg-registered-assets`. See https://github.com/sass/libsass/issues/2197
Minor updates to `assets.scss` and tests to account for this change in the output.
Verified tests passing with...
```
node-sass	3.10.0	(Wrapper)	[JavaScript]
libsass  	3.3.6	(Sass Compiler)	[C/C++]
```
and
```
node-sass	3.11.0	(Wrapper)	[JavaScript]
libsass  	3.4.0	(Sass Compiler)	[C/C++]
```
FWIW, this should have been resolvable by `unquote`ing the output when setting the key, but this still resulted in a quoted key, so this might still be an issue with `unquote` in libsass.
```scss
$eg-registered-assets: map-merge($eg-registered-assets, (
$module: …
```
=> fixes for libsass 3.4 support

lib/modules/EyeglassModule.js, test/test_modules.js
This adds a more useful error message when an invalid module path is encountered.
=> throw error if invalid module path is provided

README.md
Replace deprecated approach for passing node-sass to eyeglass with new one in the README samples.
=> Update README.md (passing node-sass to eyeglass)

lib/modules/EyeglassModules.js
The wrapping function was not correctly binding the context of `this`, which caused the `discoverModules.bind(this)` to be invalid.
=> fix discoverModules context binding issue

build/coverage.js, lib/modules/EyeglassModules.js
This issue was discovered while testing with broccoli 1.0. By default, broccoli will now use a global `tmp` path rather than local. This means that files get symlink'd in e.g. `/var/folders/...`
When eyeglass attempts to do it's module `access` check, it walks up the directory tree until it finds a `package.json`. It then uses that `package.json` to determine what dependencies can be imported.
When these files are symlink'd outside of the project workspace, eyeglass fails to find a `package.json` and thereby determines the origin scss file does not have access to the requested modules.
The fix here is to follow the symlink and check to see if the "real" file has access.
Note that we have to test _both_ the real and symlink paths. We have to test the original symlink path because it's …
=> better support for builds that use symlink

.travis.yml, lib/assets/Assets.js, package.json, test/test_assets.js
If enabled, the default assest.install will use symlinks rather then copying.
What this gives us:
* faster then copying (for those OK with symlinks)
* "best effort last write wins" makes this as concurrent asset.installs of overlapping files as safe as it can be.
TODO:
=> Add option.installWithSymlinks to toggle symlink usage

lib/assets/Assets.js, lib/assets/AssetsCollection.js, lib/assets/AssetsSource.js, package.json, test/test_assets.js
Adds a few things to allow build tools to cache the Scss generated in asAssetImport(), since otherwise this is done over and over:
- keeps a list of references to the AssetsCollections produced for modules
- adds functions to produce cache keys for AssetsSource and AssetsCollection
=> Generate cache keys for sources and collections

README.md, lib/assets/Assets.js, lib/importers/FSImporter.js, lib/importers/ImportUtilities.js, lib/index.js, lib/modules/EyeglassModules.js, lib/modules/ModuleFunctions.js, lib/util/Options.js, lib/util/SimpleCache.js, lib/util/debug.js, package-lock.json, test/test_SimpleCache.js
This adds module discovery caching to `EyeglassModules`.
The cache is fairly simple and is stored per instance of `EyeglassModules` (which translates to per `Eyeglass` instance).
I tested against a fairly large code base to see the difference between per-instance vs global caching and the savings were statistically insignificant. That said, if you are creating hundreds/thousands of eyeglass instances, it might be beneficial.
Here are some metrics of time spent in `discoverModules` (averaged across 3 runs each):
- **no caching**: 114.349s
- **per-instance caching**: 34.372s
- **global caching**: 37.052s
Other minor changes:
- updated the `canAccess` cache to share the same `SimpleCache`
- updated `debug.*` to only create functions if the debugger is enabled. this allows us to short-circuit …
=> add module discovery caching per #187

packages/eyeglass/src/assets/AssetsCollection.ts
This addresses #200, using @stefanpenner's suggestion of `\x00` as a cache key separator. This preempts any issues with `:` in a key name. I made the change and reran the tests to ensure we didn't break anything as part of this PR.
=> Fixes #200, using \x00 as cacheKey separator

packages/ember-cli-eyeglass/package.json, packages/eyeglass/src/importers/AssetImporter.ts, packages/eyeglass/src/modules/EyeglassModule.ts, packages/eyeglass/src/modules/EyeglassModules.ts
This is more efficient because it avoids a lot of filesystem access.
This also works around an issue in ember-cli where package.json files
seem to go missing during the build.
=> Don't use package.json files to locate a module from the directory structure.

eyeglass.code-workspace, packages/broccoli-eyeglass/package.json, packages/broccoli-eyeglass/src/broccoli_sass_compiler.ts, packages/broccoli-eyeglass/src/index.ts, packages/broccoli-eyeglass/tsconfig.json, packages/eyeglass/package.json, packages/eyeglass/src/Eyeglass.ts, packages/eyeglass/src/importers/AssetImporter.ts, packages/eyeglass/src/importers/FSImporter.ts, packages/eyeglass/src/importers/ImportUtilities.ts, packages/eyeglass/src/importers/ModuleImporter.ts, packages/eyeglass/src/modules/EyeglassModules.ts, packages/eyeglass/src/modules/ModuleFunctions.ts, packages/eyeglass/src/types/heimdalljs.d.ts, packages/eyeglass/tsconfig.json
Instrument eyeglass and broccoli-eyeglass for performance metrics gathering with heimdalljs.
This introduces metrics collections for the following:
* `eyeglass:broccoli:build:compileTree:<directory>` - Each broccoli tree that gets compiled by broccoli-eyeglass.
* Additional Metrics collected per tree:
* `cacheMissCount` - how many sass files had to be recompiled
* `cacheHitCount`- how many sass files were cached
* `numSassFiles` - the number of sass files.
* `nodeSassTime` - The time node-sass reports spending on compilation (includes waiting in the libuv worker queue).
* `importCount` - The number of `@import` statements encountered.
* `uniqueImportCount` - The number of `@import` statements that couldn't be deduplicated.
* eyeglass:broccoli:build:invalidation - the cost of invalidating …
=> Perf instrumentation

packages/eyeglass/sass/assets.scss, packages/eyeglass/src/assets/AssetsCollection.ts, packages/eyeglass/src/functions/normalize-uri.ts
`map-merge` is slow for maps with many keys. This patch:
* Changes the asset importer to generate Sass code that invokes `@include asset-register-all()` instead of many calls to `@include asset-register()`.
* Changes asset-register-all() to no longer delegate to `asset-register()` for each asset. Instead it passes all the assets to js where the url normalization is done in a single pass over the asset data structure.
* On non-windows machines, asset url normalization is completely skipped. This makes asset registration a single map-merge onto a map with low cardinality.
=> [eyeglass] Optimize asset registration

packages/broccoli-eyeglass/package.json, packages/broccoli-eyeglass/src/broccoli_sass_compiler.ts, packages/broccoli-eyeglass/src/concurrency.ts, yarn.lock
Empirical testing shows that Sass compilation performance is optimal when the number of physical cores is used for concurrent compilation. In this patch, I use `systeminformation` to get access to the number of physical cores because node only exposes the number of cores which includes virtual (hypervisor) cores.
Environment Variables:
* `JOBS` - a general setting for concurrency in an ember-cli build.
* `SASS_JOBS` - will override the number specified by `JOBS`. If set to `auto` it will override
the value of `JOBS` and behave as if neither of them were set.
* `UV_THREADPOOL_SIZE` - controls the number of threads in the uv threadpool. When `UV_THREADPOOL_SIZE` is unset, we will set it to the number of concurrent sass jobs we decide to use as long as this is not smaller than the default of …
=> [broccoli-eyeglass] Optimize Sass concurrency.

packages/eyeglass/src/Eyeglass.ts, packages/eyeglass/src/modules/EyeglassModules.ts, packages/eyeglass/test/fixtures/EyeglassModules/has_conflicting_versions/expected.issues, packages/eyeglass/test/test_utils.js
Eyeglass was designed to raise errors or produce warnings depending on the value of the `strictModuleVersions` option. However it seems like we never actually issued that warning or error if it was supposed to have been issued.
=> fix: Process dependency conflicts.

packages/broccoli-eyeglass/test/test_eyeglass_plugin.js, packages/eyeglass/src/modules/EyeglassModule.ts, packages/eyeglass/src/modules/EyeglassModules.ts, packages/eyeglass/test/test_modules.js
BREAKING CHANGE: this fix might change the resolved version of an eyeglass module that is both a direct dependency, a transitive dependency, and/or for which a manual module of the same name is provided.
Manual module declarations are added as direct dependencies to the root. But if the manual module was already in the module tree as a transitive dependency and a direct dependency at different versions, then adding the manual module of the transitive dependency would overwrite the direct dependency. It was never the intent for manual modules to be used to replace discovered modules, so this behavior is considered a bug which has now been fixed.
This change has three effects:
1. Manual modules that are path references to a module discovered in the
node module tree are no longer added as …
=> Ignore duplicate modules

packages/eyeglass/src/modules/EyeglassModules.ts
Simple cache for the multiple semver checks that can be done. This improves the build speed for our app and prevents some recent regressions.
=> Cache the semver compatibility checks

packages/ember-cli-eyeglass/package.json, packages/ember-cli-eyeglass/src/index.ts, packages/ember-cli-eyeglass/src/types/broccoli-funnel.d.ts, private-packages/eyeglass-test-app/.gitignore, private-packages/eyeglass-test-app/app/index.html, private-packages/eyeglass-test-app/app/styles/unprocessed.css, private-packages/eyeglass-test-app/app/templates/application.hbs, private-packages/eyeglass-test-app/tests/acceptance/eyeglass-test.js, private-packages/eyeglass-test-app/tests/index.html
`ember-cli-eyeglass` was discarding any files in the `{app,addon}/styles` directories that didn't have a sass extension. Per the ember documentation, those files should be left alone and just moved to the `assets` directory. This is what the default behavior does when there's no css preprocessors registered with ember-cli.
Note: eyeglass still doesn't respect the output path configuration, that should be done in a different patch for all of the sass and non-sass css files.
=> Non-sass files should be preserved (instead of discarded).

packages/ember-cli-eyeglass/package.json
ember-css-modules should run its build step before ember-cli-eyeglass. This allows for CSS Modules intermediate builds to work nicely with Eyeglass. (See https://github.com/salsify/ember-css-modules/blob/master/docs/PREPROCESSORS.md)
=> Should execute after ember-css-modules

packages/ember-cli-eyeglass/src/index.ts
The order of build execution between the public tree and the styles tree can vary. So this fix makes it so that we only ever return the tree with styles.
=> Fix for assets not appearing in the dist folder
